package com.ot.VendorTool.entity;

import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.validation.constraints.NotBlank;

import com.fasterxml.jackson.annotation.JsonManagedReference;

import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;

@Data
@Getter
@Setter
@Entity
public class Stock {
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@ApiModelProperty(value = "AutoGenerated")
	private long id;
	
	@NotBlank(message = "Please Enter The Stock-Type")
	@ApiModelProperty(required = true)
	private String type;
	
	@OneToMany(mappedBy = "stock",cascade = CascadeType.ALL)
	@JsonManagedReference("stock")
	private List<Product> products;
}